"""add product stock alerts

Revision ID: 159a5e7d7585
Revises: 3a2e593eda10
Create Date: 2026-08-15 10:21:10.841737
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '159a5e7d7585'
down_revision: Union[str, None] = '3a2e593eda10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_stock_alerts',
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'NOTIFIED', 'CANCELLED', name='stockalertstatus', native_enum=False, length=32), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_stock_alerts_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_product_stock_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_stock_alerts')),
    sa.UniqueConstraint('product_id', 'user_id', name='uq_product_stock_alerts_product_user')
    )
    op.create_index(op.f('ix_product_stock_alerts_created_at'), 'product_stock_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_stock_alerts_product_id'), 'product_stock_alerts', ['product_id'], unique=False)
    op.create_index('ix_product_stock_alerts_product_status', 'product_stock_alerts', ['product_id', 'status'], unique=False)
    op.create_index(op.f('ix_product_stock_alerts_status'), 'product_stock_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_product_stock_alerts_user_id'), 'product_stock_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_stock_alerts_user_id'), table_name='product_stock_alerts')
    op.drop_index(op.f('ix_product_stock_alerts_status'), table_name='product_stock_alerts')
    op.drop_index('ix_product_stock_alerts_product_status', table_name='product_stock_alerts')
    op.drop_index(op.f('ix_product_stock_alerts_product_id'), table_name='product_stock_alerts')
    op.drop_index(op.f('ix_product_stock_alerts_created_at'), table_name='product_stock_alerts')
    op.drop_table('product_stock_alerts')
    # ### end Alembic commands ###
