"""initial schema

Revision ID: 3a2e593eda10
Revises: 
Create Date: 2026-08-15 09:06:22.374683
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a2e593eda10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('admin_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.Enum('ADMIN_CREATED_PRODUCT', 'ADMIN_UPDATED_PRODUCT', 'ADMIN_DELETED_PRODUCT', 'ADMIN_TOGGLED_PRODUCT', 'ADMIN_CREATED_PLAN', 'ADMIN_UPDATED_PLAN', 'ADMIN_DELETED_PLAN', 'ADMIN_TOGGLED_PLAN', 'ADMIN_CHANGED_PRICE', 'ADMIN_ADDED_STOCK', 'ADMIN_REMOVED_STOCK', 'ADMIN_IMPORTED_CODES', 'ADMIN_CONFIRMED_PAYMENT', 'ADMIN_REJECTED_PAYMENT', 'ADMIN_FULFILLED_ORDER', 'ADMIN_CANCELLED_ORDER', 'ADMIN_REFUNDED_ORDER', 'ADMIN_SENT_BROADCAST', 'ADMIN_SENT_STOCK_NOTIFICATION', 'ADMIN_BLOCKED_USER', 'ADMIN_UNBLOCKED_USER', 'ADMIN_UPDATED_PAYMENT_METHOD', 'ADMIN_UPDATED_SETTINGS', 'ADMIN_CREATED_CATEGORY', 'ADMIN_UPDATED_CATEGORY', 'ADMIN_DELETED_CATEGORY', 'ADMIN_CREATED_COUPON', 'ADMIN_UPDATED_COUPON', name='adminaction', native_enum=False, length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_logs'))
    )
    op.create_index(op.f('ix_admin_logs_action'), 'admin_logs', ['action'], unique=False)
    op.create_index('ix_admin_logs_action_created', 'admin_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_admin_logs_admin_created', 'admin_logs', ['admin_telegram_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_admin_logs_created_at'), 'admin_logs', ['created_at'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_sort_order'), 'categories', ['sort_order'], unique=False)
    op.create_table('coupons',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('type', sa.Enum('PERCENT', 'FIXED', name='coupontype', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('min_order_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('code', name=op.f('uq_coupons_code'))
    )
    op.create_index(op.f('ix_coupons_created_at'), 'coupons', ['created_at'], unique=False)
    op.create_table('payment_methods',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('account_identifier', sa.String(length=255), nullable=True),
    sa.Column('network', sa.String(length=64), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_screenshot', sa.Boolean(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_methods')),
    sa.UniqueConstraint('code', name=op.f('uq_payment_methods_code'))
    )
    op.create_index(op.f('ix_payment_methods_created_at'), 'payment_methods', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_methods_sort_order'), 'payment_methods', ['sort_order'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_settings_key'))
    )
    op.create_index(op.f('ix_settings_created_at'), 'settings', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('has_blocked_bot', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('block_reason', sa.String(length=255), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index('ix_users_is_active_is_blocked', 'users', ['is_active', 'is_blocked'], unique=False)
    op.create_index(op.f('ix_users_last_activity_at'), 'users', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('admins',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'STAFF', name='adminrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('granted_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('last_action_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admins_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('user_id', name=op.f('uq_admins_user_id'))
    )
    op.create_index(op.f('ix_admins_created_at'), 'admins', ['created_at'], unique=False)
    op.create_index(op.f('ix_admins_role'), 'admins', ['role'], unique=False)
    op.create_index(op.f('ix_admins_telegram_id'), 'admins', ['telegram_id'], unique=True)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_REJECTED', 'PAID', 'PROCESSING', 'READY', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('coupon_id', sa.BigInteger(), nullable=True),
    sa.Column('coupon_code', sa.String(length=48), nullable=True),
    sa.Column('delivery_content', sa.Text(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('stock_settled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_orders_coupon_id_coupons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_expires_at'), 'orders', ['expires_at'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_telegram_id'), 'orders', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('image_file_id', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    op.create_index('ix_products_active_sort', 'products', ['is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index('ix_products_featured_sort', 'products', ['is_featured', 'sort_order'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('order_status_history',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_REJECTED', 'PAID', 'PROCESSING', 'READY', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus', native_enum=False, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING_PAYMENT', 'PAYMENT_SUBMITTED', 'PAYMENT_REJECTED', 'PAID', 'PROCESSING', 'READY', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('changed_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_history_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_history'))
    )
    op.create_index(op.f('ix_order_status_history_created_at'), 'order_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('method_id', sa.BigInteger(), nullable=True),
    sa.Column('method_code', sa.String(length=32), nullable=True),
    sa.Column('method_name', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'CONFIRMED', 'REJECTED', name='paymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('proof_file_id', sa.String(length=255), nullable=True),
    sa.Column('proof_file_unique_id', sa.String(length=128), nullable=True),
    sa.Column('customer_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['payment_methods.id'], name=op.f('fk_payments_method_id_payment_methods'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_method_id'), 'payments', ['method_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_order_status', 'payments', ['order_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_created', 'payments', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('plans',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=80), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('sold_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('delivery_type', sa.Enum('MANUAL', 'CODE', 'ACCOUNT', 'INFORMATION', name='deliverytype', native_enum=False, length=32), nullable=False),
    sa.Column('delivery_note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_plans_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('product_id', 'name', name='uq_plans_product_id_name')
    )
    op.create_index(op.f('ix_plans_created_at'), 'plans', ['created_at'], unique=False)
    op.create_index('ix_plans_product_active_sort', 'plans', ['product_id', 'is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_plans_product_id'), 'plans', ['product_id'], unique=False)
    op.create_index('ix_plans_stock', 'plans', ['stock_quantity'], unique=False)
    op.create_table('broadcasts',
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_file_id', sa.String(length=255), nullable=True),
    sa.Column('button_text', sa.String(length=64), nullable=True),
    sa.Column('button_callback', sa.String(length=64), nullable=True),
    sa.Column('audience', sa.Enum('ALL_USERS', 'ACTIVE_USERS', 'CUSTOMERS', 'INTERESTED_USERS', name='broadcastaudience', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'COMPLETED', 'CANCELLED', 'FAILED', name='broadcaststatus', native_enum=False, length=32), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('failed_telegram_ids', sa.Text(), nullable=True),
    sa.Column('created_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_broadcasts_plan_id_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts'))
    )
    op.create_index(op.f('ix_broadcasts_created_at'), 'broadcasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_broadcasts_status'), 'broadcasts', ['status'], unique=False)
    op.create_index('ix_broadcasts_status_created', 'broadcasts', ['status', 'created_at'], unique=False)
    op.create_table('inventory',
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', 'DISABLED', name='inventorystatus', native_enum=False, length=32), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('added_by_telegram_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_inventory_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_inventory_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory'))
    )
    op.create_index(op.f('ix_inventory_created_at'), 'inventory', ['created_at'], unique=False)
    op.create_index('ix_inventory_order', 'inventory', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventory_plan_id'), 'inventory', ['plan_id'], unique=False)
    op.create_index('ix_inventory_plan_status', 'inventory', ['plan_id', 'status'], unique=False)
    op.create_index(op.f('ix_inventory_status'), 'inventory', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('type', sa.Enum('STOCK_AVAILABLE', 'NEW_PRODUCT', 'PRICE_CHANGE', 'PROMOTION', 'ORDER_UPDATE', 'PAYMENT_UPDATE', 'SYSTEM', name='notificationtype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('is_broadcast', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_notifications_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_notifications_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_notifications_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_order_id'), 'notifications', ['order_id'], unique=False)
    op.create_index(op.f('ix_notifications_plan_id'), 'notifications', ['plan_id'], unique=False)
    op.create_index(op.f('ix_notifications_product_id'), 'notifications', ['product_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_type_created', 'notifications', ['type', 'created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('plan_name', sa.String(length=160), nullable=False),
    sa.Column('duration', sa.String(length=80), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_order_items_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_created_at'), 'order_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_plan_id'), 'order_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('stock_alerts',
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'NOTIFIED', 'CANCELLED', name='stockalertstatus', native_enum=False, length=32), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_stock_alerts_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stock_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_alerts')),
    sa.UniqueConstraint('plan_id', 'user_id', name='uq_stock_alerts_plan_user')
    )
    op.create_index(op.f('ix_stock_alerts_created_at'), 'stock_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_alerts_plan_id'), 'stock_alerts', ['plan_id'], unique=False)
    op.create_index('ix_stock_alerts_plan_status', 'stock_alerts', ['plan_id', 'status'], unique=False)
    op.create_index(op.f('ix_stock_alerts_status'), 'stock_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_stock_alerts_user_id'), 'stock_alerts', ['user_id'], unique=False)
    op.create_table('notification_recipients',
    sa.Column('notification_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('delivery_state', sa.Enum('PENDING', 'SENT', 'FAILED', 'SKIPPED', name='deliverystate', native_enum=False, length=32), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_recipients_notification_id_notifications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_recipients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_recipients')),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_notification_recipients_pair')
    )
    op.create_index(op.f('ix_notification_recipients_created_at'), 'notification_recipients', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_recipients_notification_id'), 'notification_recipients', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_recipients_user_id'), 'notification_recipients', ['user_id'], unique=False)
    op.create_index('ix_notification_recipients_user_read', 'notification_recipients', ['user_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_recipients_user_read', table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_user_id'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_notification_id'), table_name='notification_recipients')
    op.drop_index(op.f('ix_notification_recipients_created_at'), table_name='notification_recipients')
    op.drop_table('notification_recipients')
    op.drop_index(op.f('ix_stock_alerts_user_id'), table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_status'), table_name='stock_alerts')
    op.drop_index('ix_stock_alerts_plan_status', table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_plan_id'), table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_created_at'), table_name='stock_alerts')
    op.drop_table('stock_alerts')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_plan_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_created_at'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_notifications_type_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_product_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_plan_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_order_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_inventory_status'), table_name='inventory')
    op.drop_index('ix_inventory_plan_status', table_name='inventory')
    op.drop_index(op.f('ix_inventory_plan_id'), table_name='inventory')
    op.drop_index('ix_inventory_order', table_name='inventory')
    op.drop_index(op.f('ix_inventory_created_at'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('ix_broadcasts_status_created', table_name='broadcasts')
    op.drop_index(op.f('ix_broadcasts_status'), table_name='broadcasts')
    op.drop_index(op.f('ix_broadcasts_created_at'), table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_index('ix_plans_stock', table_name='plans')
    op.drop_index(op.f('ix_plans_product_id'), table_name='plans')
    op.drop_index('ix_plans_product_active_sort', table_name='plans')
    op.drop_index(op.f('ix_plans_created_at'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index('ix_payments_status_created', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index('ix_payments_order_status', table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_method_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_created_at'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index('ix_products_featured_sort', table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index('ix_products_active_sort', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_orders_user_status', table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_telegram_id'), table_name='orders')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_expires_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_admins_telegram_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_role'), table_name='admins')
    op.drop_index(op.f('ix_admins_created_at'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_last_activity_at'), table_name='users')
    op.drop_index('ix_users_is_active_is_blocked', table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_created_at'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_payment_methods_sort_order'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_created_at'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_coupons_created_at'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_categories_sort_order'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_admin_logs_created_at'), table_name='admin_logs')
    op.drop_index('ix_admin_logs_admin_created', table_name='admin_logs')
    op.drop_index('ix_admin_logs_action_created', table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_action'), table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
